### DISCUSSION TITLE
Domain-validated TLS Certificates for Control Plane endpoints

### DISCUSSION THREAD

**Discussion by Shark** [rackerlabs/spot#116] [Feature Requests]
Rackspace currently doesn't seem to provision domain-validated TLS certificates for the control plane endpoints.

For my cluster in *uk-lon-1*, the kubeconfig contains:

```yaml
apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: true
      server: https://hcp-UUID.spot.rackspace.com/
    name: mycluster
...
```

The certificate is:

```
$ openssl s_client -connect hcp-UUID.spot.rackspace.com:443 -showcerts
CONNECTED(00000003)
depth=0 CN = kube-apiserver
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = kube-apiserver
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = kube-apiserver
verify return:1
---
Certificate chain
 0 s:CN = kube-apiserver
   i:CN = kubernetes
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: May  7 01:46:09 2025 GMT; NotAfter: May  7 01:51:09 2026 GMT
```

I love Rackspace Spot and it's a truly great service. Getting proper TLS certs in place should be possible without too much effort for much gain in terms of security. 🙏
