### DISCUSSION TITLE
NodePort to publically expose pod listening on UDP

### DISCUSSION THREAD

**Discussion by indyfiero2m4** [rackerlabs/spot#58] [How do I?] [answered]
So I've tried this with the actual application I want to use. BUT.

If I create a nodeport for a BusyBox listening on UDP 4000 and find my public IP of my node from the kubernets console. Then try to send data to it with netcat I get nothing.

I tried setting up an nginx pod as well and just had it listening on 80 via nodeport and couldn't get to it either.

Is there a surefire way to get the right node public IP and does anyone have an example of a nodeport yml that works for UDP?

**Comment by sirishkr** [comment]
To find the public IP on your node you should be able to:
$kubectl get nodes -o wide

Then you should be able to use something like this:
```
apiVersion: v1
kind: Service
metadata:
name: my-udp-service
spec:
selector:
app: my-udp-app
ports:
- port: 5000 # Service port
targetPort: 5000 # Pod port
protocol: UDP
nodePort: 30001 # Specific NodePort number
type: NodePort
```

**Reply by indyfiero2m4** [reply]
Should I see it here: 

![image](https://github.com/user-attachments/assets/c4fb7516-40bf-476b-8861-3ce749c47914)

Or do I use the one under internal IP?

**Reply by sirishkr** [reply]
@indyfiero2m4 can you try using the IP listed under internal IP and let us know if that doesn't work?

**Reply by indyfiero2m4** [reply]
Still no luck. I setup another nginx pod listening on tcp port 80. Here is the nodeport svc I deployed for it:

```yml
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    run: nginx-pod
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
    nodePort: 30001 # Specific NodePort number
  selector:
    run: nginx-pod
```
I can port forward that service locally and it works fine. However when I try to access it via the internal IP listed on the node I get connection failed:

![image](https://github.com/user-attachments/assets/936c3b64-1f9e-4513-a171-1f4f63d4df8b)

**Reply by incidentally-nameless** [reply]
Is your nginx server itself listening on 0.0.0.0? I had an issue where I could hit the service internally (and using kubectl port-forward) but externally it failed because it wasn't listening on all IPs

I mention this because I've been able to use NodePort successfully for TCP traffic on my nodes

**Reply by sahil-lakhwani** [reply]
@indyfiero2m4 Can you please check and list the endpoints of the service here

```
kubectl get endpoints <service-name>
```

**Reply by indyfiero2m4** [reply]
Here's what I get
`nginx-svc   10.20.70.86:80   9h`

**Reply by indyfiero2m4** [reply]
@sahil-lakhwani, @sirishkr: any further ideas?

**Reply by sahil-lakhwani** [reply, marked as answer]
@indyfiero2m4 Can you please check if the nginx pod itself is listening to UDP traffic?

I just tried the following spec which runs a UDP server in a pod, which is then exposed by a NodePort service over UDP.

```
apiVersion: v1
kind: Pod
metadata:
  name: udp-server
  labels:
    app: udp-server
    tier: udp
spec:
  containers:
  - name: udp-echo-server
    image: mendhak/udp-listener
    ports:
    - containerPort: 5005
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: udp-nodeport-service
spec:
  type: NodePort
  selector:
    app: udp-server
    tier: udp
  ports:
    - protocol: UDP
      port: 5005
      targetPort: 5005
      nodePort: 31000
```

I was able to verify by running `nc  -u <node-ip> 31000` and could see the logs in the udp-server pod.
